# MIT License

# Copyright (c) 2022 EASE lab

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# fibonacciORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

version: "3.9"
services:
  ## Fibonacci ---------------------------------
  fibonacci-go:
    image: vhiveease/fibonacci-go:latest
    container_name: function
    entrypoint:
      - /app/server
      - -addr=0.0.0.0:50051
    ports:
      - target: 50051
        published: 50000

  fibonacci-nodejs:
    image: vhiveease/fibonacci-nodejs:latest
    container_name: function
    entrypoint:
      - node
      - server.js
      - --addr=0.0.0.0
      - --port=50051
    ports:
      - target: 50051
        published: 50000

  fibonacci-python:
    image: vhiveease/fibonacci-python:latest
    container_name: function
    entrypoint:
      - python
      - /app/server.py
      - --addr=0.0.0.0
      - --port=50051
    ports:
      - target: 50051
        published: 50000


  ## AES ---------------------------------
  aes-go:
    image: vhiveease/aes-go:latest
    container_name: function
    entrypoint:
      - /app/server
      - -addr=0.0.0.0:50051
    ports:
      - target: 50051
        published: 50000

  aes-nodejs:
    image: vhiveease/aes-nodejs:latest
    container_name: function
    entrypoint:
      - node
      - server.js
      - --addr=0.0.0.0
      - --port=50051
    ports:
      - target: 50051
        published: 50000

  aes-python:
    image: vhiveease/aes-python:latest
    container_name: function
    entrypoint:
      - python
      - /app/server.py
      - --addr=0.0.0.0
      - --port=50051
    ports:
      - target: 50051
        published: 50000


  ## Authentication -----------------------
  auth-go:
    image: vhiveease/auth-go:latest
    container_name: function
    entrypoint:
      - /app/server
      - -addr=0.0.0.0:50051
    ports:
      - target: 50051
        published: 50000

  auth-nodejs:
    image: vhiveease/auth-nodejs:latest
    container_name: function
    entrypoint:
      - node
      - server.js
      - --addr=0.0.0.0
      - --port=50051
    ports:
      - target: 50051
        published: 50000

  auth-python:
    image: vhiveease/auth-python:latest
    container_name: function
    entrypoint:
      - python
      - /app/server.py
      - --addr=0.0.0.0
      - --port=50051
    ports:
      - target: 50051
        published: 50000