# MIT License
#
# Copyright (c) 2021 Mert Bora Alper and EASE lab
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Execute this playbook using
#   GH_ACCESS_TOKEN=... ansible-playbook -u YOUR_SSH_USERNAME -i REMOTE_HOSTNAME, create-runner.yaml
#
# To create N=10 runners, use
#   for run in {1..10}; do GH_ACCESS_TOKEN=... ansible-playbook -u YOUR_SSH_USERNAME -i REMOTE_HOSTNAME, create-runner.yaml; done

---
- name: Create GitHub Runners for gem5 CI
  hosts: all
  tasks:
    # - name: Get GitHub runner token
    #   uri:
    #     method: POST
    #     url: https://api.github.com/repos/ease-lab/vSwarm-u/actions/runners/registration-token
    #     headers:
    #       Accept: application/vnd.github.v3+json
    #       Authorization: "token {{ lookup('env', 'GH_ACCESS_TOKEN') }}"
    #     status_code: 201
    #   register: registration

    - name: Generate a random runner name
      shell: 'printf "$(shuf -n1 /usr/share/dict/predicates)-$(shuf -n1 /usr/share/dict/objects)"'
      register: runner_name

    - name: Print the generated name
      ansible.builtin.debug:
        var: runner_name.stdout

    # - name: Create working directory for the runner
    #   become: yes
    #   ansible.builtin.file:
    #     path: /tmp/_work-{{ runner_name.stdout }}/
    #     state: directory
    #     mode: '0755'

    - name: Start the git-hub runner
      command: |
        sudo docker run --name github-runner-build --rm \
          --privileged --cap-add=ALL \
          -e RESOURCES=/tmp/resources/ \
          -e RUNNER_NAME="gem5-build-runner-{{ cluster_name.stdout }}" \
          -e RUNNER_TOKEN={{ registration.json.token }} \
          -v /var/run/docker.socker.sock:/var/run/docker.sock \
          -v {{ lookup('env', 'RESOURCES') }}:/tmp/resources/
          vhiveease/qemu-test-runner