# MIT License
#
# Copyright (c) 2022 David Schall and EASE lab
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


# Execute this playbook using
#  ansible-playbook -u YOUR_SSH_USERNAME -i REMOTE_HOSTNAME, setup-host.yaml

---
- name: Setup vSwarm-u runner host
  hosts: all
  vars:
    RESOURCES: /resources/
  tasks:

    - name: Run the github runner
      become: yes
      shell: |
        GH_ACCESS_TOKEN={{ lookup('env', 'GH_ACCESS_TOKEN') }}
        TMP=$(date +%s%N | cut -b10-19)
        docker run --rm -d --name github-runner-${TMP} \
                    -e REPO_URL="https://github.com/vhive-serverless/vSwarm-u" \
                    -e ACCESS_TOKEN="${GH_ACCESS_TOKEN}" \
                    -e RUNNER_NAME="vswarm-u-build-runner-${TMP}" \
                    -e RUNNER_WORKDIR="/tmp/_work" \
                    -e RUNNER_GROUP=default \
                    -e LABELS="vswarm-u-build" \
                    --privileged --cap-add=ALL \
                    -v /tmp/github-runner-your-repo:/tmp/github-runner-your-repo \
                        myoung34/github-runner:latest
